 - hosts: localhost
   become: true
   tasks:

  # - name: Install Git via APT
  #   apt:
  #     name:
  #     - git
  #     state: latest
  #     cache_valid_time: 3600
   
   - name: Create the app on CapRover
     ansible.builtin.raw:
       python3 susapi.py git True http://"{{ item }}":3000
     loop: "{{ groups['development']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
     ignore_errors: yes

   - name: Setup docker image and port mapping
     ansible.builtin.raw:
       python3 git-installer.py git http://"{{ item }}":3000
     loop: "{{ groups['development']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
