 - hosts: development
   tasks:

   - name: copy script
     copy:
       src: ~/devops-turnkey-playbooks/buckets.py
       dest: ~/buckets.py

   - name: run script
     ansible.builtin.raw:
       python3 buckets.py
