 - hosts: development
   tasks:

   - name: copy script
     copy:
       src: ~/devops-turnkey-playbooks/buckets.py
       dest: ~/buckets.py

   - name: run script
     become: true
     ansible.builtin.raw:
       python3 buckets.py niniryjuns

   - name: copy overseer key
     become: true
     ansible.builtin.raw:
       python3 buckets.py overseer-keys
