 - hosts: development
   tasks:

   - name: copy script
     copy:
       src: ~/devops-turnkey-playbooks/buckets.py
       dest: ~/buckets.py

   - name: copy bash script
       src: ~/devops-turnkey-playbooks/bucketScript.sh
       dest: ~/bucketScript.sh

   - name: install boto3
     become: true
     ansible.builtin.raw:
       pip3 install boto3

   - name: run script
     become: true
     ansible.builtin.raw:
       bash bucketScript.sh niniryjuns {{ awskeyid }} {{ awskey }}

   - name: copy overseer key
     become: true
     ansible.builtin.raw:
       bash bucketScript.sh overseer-keys {{ awskeyid }} {{ awskey }}
