 - hosts: localhost
   tasks:
  
   - name: copy ssh keys
     ansible.builtin.raw:
       ssh ubuntu@{{ item }} 'sudo python3 buckets.py niniryjuns{{ index }}'
     loop: "{{ groups['development']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index

   - name: copy overseer key
     ansible.builtin.raw:
       ssh ubuntu@{{ item }} 'sudo python3 buckets.py overseer-keys'
     loop: "{{ groups['development']|flatten(levels=1) }}" # change to dev group
