 - hosts: development
   tasks:

   - name: copy script
     copy:
       src: ~/devops-turnkey-playbooks/buckets.py
       dest: ~/buckets.py

   - name: run script
     become: true
     raw:
       python3 buckets.py /home/ubuntu/.ssh/id_rsa.pub
