 - hosts: localhost
   become: true
   tasks:

   - name: jenkins uninstaller
     ansible.builtin.raw:
       python jenkins-uninstaller.py jenkins http://captain.captain."{{ item }}".sslip.io
     loop: "{{ groups['testservers']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
