---
- name: Make an ssh agent on ansible master 
  hosts: localhost
  vars:
    keyname: yourKeyName
    keypath: ~/.ssh/
    ending: .pem
  tasks:
    - name: Run agent
      raw: ssh-agent bash
   
    - name: Add key
      raw: ssh-add "{{ keyname + keypath + ending }}"

