 - hosts: localhost
   become: true
   tasks:
   
   - name: Create the app on CapRover
     ansible.builtin.raw:
       python susapi-tomcat.py tomcat http://"{{ item }}":3000
     loop: "{{ groups['application']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
     ignore_errors: yes

   - name: Setup docker image and port mapping
     ansible.builtin.raw:
       python config-tomcat.py tomcat http://"{{ item }}":3000
     loop: "{{ groups['application']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
