 - hosts: localhost
   become: true
   tasks:

   - name: Git uninstaller
     ansible.builtin.raw:
       python tomcat-uninstaller.py tomcat"{{ index }}" http://captain.captain."{{ item }}".sslip.io
     loop: "{{ groups['testservers']|flatten(levels=1) }}" # change to dev group
     loop_control:
       index_var: index
     args:
       warn: false
